### ISSUE TITLE
No headers in `clerk/table`

### ISSUE THREAD

**Issue by cstby** [nextjournal/clerk#10]
I'm currently using Clerk 0.2.214.

If I execute the following contrived example, I get the following results.
```
(clerk/table
 [{:shape "round"
   :color "blue"}
  {:shape "square"
   :color "blue"}
  {:shape "square"
   :color "red"}])
```
![image](https://user-images.githubusercontent.com/45189177/140427616-86977fa7-50d4-4e6b-921b-ca62ded31c32.png)

I would expect to see "shape" and "color" as the bolded headers of this table. This issue was not present when I was using version 0.1.164 a few weeks ago.

**Comment by mk** [comment]
Hey, thanks for the report. The table viewer in the current version is more a prototype than a useable thing. Good news is that we're working on something actually usable in #5. Hope we'll be able to wrap it up in the coming days.

**Comment by cstby** [comment]
I'll look forward to checking that out! Thanks for all your work, by the way. Clerk is already really awesome, and I'm excited to see all the changes you're planning. :)
