### ISSUE TITLE
Better linting for render-fns

### ISSUE THREAD

**Issue by borkdude** [nextjournal/clerk#101]
As discussed on Slack, but posting here to keep better track of this issue:

The `:render-fn` option is a quoted expression that is passed from the backend to the front-end and evaluated there. Currently when writing render fns, one does not get any linting feedback from clj-kondo since clj-kondo treats a quoted expression just as a piece of data without any special meaning.

Using a clj-kondo hook, it is possible to restore linting feedback. But clj-kondo hooks need something to hook on to. One solution could be to introduce a "marker" macro or even just a function, `clerk/render-fn` which just returns what you pass to it:

```
:render-fn (clerk/render-fn '(fn [_] ...))
```

so clj-kondo is able to "hook" on to this expression and can transform it to an unquoted expression, so you get proper linting. Preserving the quoted expression as it is within the call to `render-fn` takes care of "false positives" in Cursive or other editors that have their own way of looking at the code.

To resolve the usage of the alias `v` users can introduce a synthetic alias using `[nextjournal.viewer :as-alias v]` which will not require that dependency to be available at runtime but will help clj-kondo understand what the user means with `v/...`.

Both things (`render-fn` + `:as-alias`) are completely optional but do allow for better linting for users that want to have that.

<img width="1192" alt="Screen Shot 2022-02-28 at 15 50 11" src="https://user-images.githubusercontent.com/284934/156004781-e5f24eca-17f7-4140-94c7-389bd1b1fa33.png">

<img width="714" alt="Screen Shot 2022-02-28 at 15 56 45" src="https://user-images.githubusercontent.com/284934/156004851-0cc1bd2b-bcf6-43f3-8e56-a5bc7f62408f.png">

The above screenshots were made with the branch `clj-kondo-lint-fn`.

**Comment by mk** [comment]
Is is also possible to write a clj-kondo hook that gives linting without changes to the code? So either infer that the map in the `mermaid` var is being used in a `clerk/with-viewer` call or alternatively apply a certain validation based on the `:render-fn` key inside a map?

**Comment by borkdude** [comment]
A simpler idea:

Just put the render fn in a `.cljs` file and slurp the cljs file. This needs the `:render-fn` to be able to accept a string but I think clerk is serializing it as a string anyway already? 

This would also work better for when we have a SCI nREPL server in the browser so you can eval your function directly in the browser.

**Comment by borkdude** [comment]
Will be fixed by #190

**Comment by mk** [comment]
We implemented better linting with the clj-kondo hooks in #318.
