### ISSUE TITLE
CSS size

### ISSUE THREAD

**Issue by prepor** [nextjournal/clerk#11]
Hi. Bundled clerk currently contains 3.2 Mb CSS file. As I see the project used to `purge` instruction for Tailwindcss, but it was disabled with a comment "Move to non-jit compiled tailwind stylesheet, purging doesn't work nicely with custom viewers".

Could you please elaborate this decision, how exactly it doesn't play nicely with custom viewers?

Thank you

**Comment by mk** [comment]
Hi, before disabling [tailwind jit](https://tailwindcss.com/docs/just-in-time-mode) in 875b05985de3e3e2a7577d36ff0ce7b8b0a1e4d4, any css class not yet used will get purged from the final css. 

This would mean that folks can't use any classes not already used by Clerk without setting up a css build pipeline. See [Rule 30](https://storage.googleapis.com/nextjournal-snapshots/clerk/build/fd79f7504ebffaa27958e4e05264b0ad2f650182/index.html#/notebooks%2Frule_30.clj) as an example of such a notebook, where some of the boder styles `bg-white border-solid border-2 border-black` would have been purged then.

We do want to support letting folks opt into setting up a css build pipeline to get smaller css files but I think it's the right tradeoff to make for now.
