### ISSUE TITLE
rendering keywords with spaces fails

### ISSUE THREAD

**Issue by behrica** [nextjournal/clerk#116]
rendering this:

```clojure
[(hash-map (keyword "N hello") [1 2 3])]
```

in clerk fails with

```
{
    "message": "The map literal starting with :path contains 7 form(s). Map literals must contain an even number of forms.",
    "data": {
        "meta": null,
        "O": 3,
        "K": [
            {
                "Lb": null,
                "name": "type",
                "X": "type",
                "$d": 1174270348,
                "I": 2153775105,
                "S": 4096
            },
            {
                "Lb": "edamame",
                "name": "error",
                "X": "edamame/error",
                "$d": 882529634,
                "I": 2153775105,
                "S": 4096
            },
            {
                "Lb": null,
                "name": "line",
                "X": "line",
                "$d": 212345235,
                "I": 2153775105,
                "S": 4096
            },
            1,
            {
                "Lb": null,
                "name": "column",
                "X": "column",
                "$d": 2078222095,
                "I": 2153775105,
                "S": 4096
            },
            98
        ],
        "N": null,
        "I": 16647951,
        "S": 139268
    },
    "Ae": null,
    "name": "Error",
    "stack": "Error: The map literal starting with :path contains 7 form(s). Map literals must contain an even number of forms.\n    at new bq (https://storage.googleapis.com/nextjournal-cas-eu/data/8VwU4isthVmn9MopRQfnkSALhbgqYxLqKo5kcDegZMKgH38QUQUt7keu6sqPqCKbv8RgjwnVBvLu96uaQ8xhGQ1sSH:2202:26)\n    at Function.cq.j (https://storage.googleapis.com/nextjournal-cas-eu/data/8VwU4isthVmn9MopRQfnkSALhbgqYxLqKo5kcDegZMKgH38QUQUt7keu6sqPqCKbv8RgjwnVBvLu96uaQ8xhGQ1sSH:2204:71)\n    at Function.cq.h (https://storage.googleapis.com/nextjournal-cas-eu/data/8VwU4isthVmn9MopRQfnkSALhbgqYxLqKo5kcDegZMKgH38QUQUt7keu6sqPqCKbv8RgjwnVBvLu96uaQ8xhGQ1sSH:2204:30)\n    at gS (https://storage.googleapis.com/nextjournal-cas-eu/data/8VwU4isthVmn9MopRQfnkSALhbgqYxLqKo5kcDegZMKgH38QUQUt7keu6sqPqCKbv8RgjwnVBvLu96uaQ8xhGQ1sSH:2493:353)\n    at Pca (https://storage.googleapis.com/nextjournal-cas-eu/data/8VwU4isthVmn9MopRQfnkSALhbgqYxLqKo5kcDegZMKgH38QUQUt7keu6sqPqCKbv8RgjwnVBvLu96uaQ8xhGQ1sSH:2507:68)\n    at oS (https://storage.googleapis.com/nextjournal-cas-eu/data/8VwU4isthVmn9MopRQfnkSALhbgqYxLqKo5kcDegZMKgH38QUQUt7keu6sqPqCKbv8RgjwnVBvLu96uaQ8xhGQ1sSH:2514:395)\n    at pS (https://storage.googleapis.com/nextjournal-cas-eu/data/8VwU4isthVmn9MopRQfnkSALhbgqYxLqKo5kcDegZMKgH38QUQUt7keu6sqPqCKbv8RgjwnVBvLu96uaQ8xhGQ1sSH:2521:363)\n    at jS (https://storage.googleapis.com/nextjournal-cas-eu/data/8VwU4isthVmn9MopRQfnkSALhbgqYxLqKo5kcDegZMKgH38QUQUt7keu6sqPqCKbv8RgjwnVBvLu96uaQ8xhGQ1sSH:2520:243)\n    at iS (https://storage.googleapis.com/nextjournal-cas-eu/data/8VwU4isthVmn9MopRQfnkSALhbgqYxLqKo5kcDegZMKgH38QUQUt7keu6sqPqCKbv8RgjwnVBvLu96uaQ8xhGQ1sSH:2494:249)\n    at oS (https://storage.googleapis.com/nextjournal-cas-eu/data/8VwU4isthVmn9MopRQfnkSALhbgqYxLqKo5kcDegZMKgH38QUQUt7keu6sqPqCKbv8RgjwnVBvLu96uaQ8xhGQ1sSH:2514:362)"
}

```

**Comment by philomates** [comment]
As far as I understand, Clerk uses EDN to transport data from the JVM to the browser and spaces in keywords doesn't seem to work with EDN (some context in https://github.com/ptaoussanis/sente/issues/251)

Transit does support this but it looks like there is already a lot of code in place around EDN, via [edamame](https://github.com/borkdude/edamame), so I imagine that migrating to transit isn't worth it.

I'm not super familiar with the trade-offs between the two formats, so I'm curious: would it be theoretically possible to switch from EDN to Transit without loosing existing features? @mk and @borkdude, do you know?

**Comment by borkdude** [comment]
Evaluating:
``` 
[(hash-map (keyword "N hello") [1 2 3])]
;;=> [{:N hello [1 2 3]}]
```
Parsing `[{:N hello [1 2 3]}]` is what you see the error message about,

**Comment by philomates** [comment]
I think it breaks at several places, but one I expect would be usages of edamame in `nextjournal.clerk.hashing/read-string`
where `(nextjournal.clerk.hashing/read-string ":a a") ;; => :a`
The other somehow the notebook shows the viewer/value datastructure instead of rendering the keyword. When it renders this datastructure it shows the error mentioned by @behrica 
![20220407_14h59m54s_grim](https://user-images.githubusercontent.com/94817/162204642-adc57ed6-1ed2-47d3-b55b-56df0eba13f5.png)

**Comment by borkdude** [comment]
I'll look at this later today.

**Comment by mk** [comment]
I think the problem is that programmatically constructed keywords or symbols (via `keyword` and `symbol`) must not be readable so unsure if there's something actionable here.

See also [Why is it possible to create keywords that can’t be read by the reader?](https://clojure.org/guides/faq#unreadable_keywords)

**Comment by borkdude** [comment]
> I'm not super familiar with the trade-offs 

I think one answer could be: we're not trying to be better than Clojure, EDN or JSON.

**Comment by behrica** [comment]
The philosophical questions is more, how "compatible" Clerk need to be with "an arbitrary .clj file".

So far I have the expectation that any **valid** .clj file can be rendered/executed  as well by Clerk without error.
(Otherwise it is a bug in Clerk)

But maybe it is a too wide expectation , but current Clerk announces as 
```
Clerk takes a Clojure namespace and turns it into a notebook:
```

which implies "takes any namespace".

I made similar comments regarding the fact that the Clerk caching cannot cache everything.

Eventually we should communicate more clearly, that Clerk has certain requirements for being able to execute / render a Clojure namespace. (and keywords with spaces would then be unsupported to render).

I would still say, Clerk should "guaranty" to "execute" all lines of any .clj file (if valid Clojure).
It might "not render some values"   (or not cache them), but we should striver for "successful execution".

**Comment by behrica** [comment]
Maybe it would make sense to catch the "sci read error" on ClojureScript side and show in the browser a more friendly message, which indicates that the current value "cannot be rendered by Clerk".

**Comment by behrica** [comment]
I just learned that "spaces are illegal in keywords", even though they can be created via the keyword function.
In this case I would suggest as well to close this issue.

**Comment by mk** [comment]
> I would suggest as well to close this issue.

I agree 🙃. Also agree that there's plenty of holes in the documentation that need to be filled but I don't want to track those in issues just yet.

**Comment by mk** [comment]
Since dropping the edn in edn encoding for results this leads to a global failure (instead of being contained to a single result). This occurred again today https://clojurians.slack.com/archives/C035GRLJEP8/p1670105206417629
