### ISSUE TITLE
Feature: Some way to skip display of certain code-blocks

### ISSUE THREAD

**Issue by wildwestrom** [nextjournal/clerk#13]
![Screen Shot 2021-11-07 at 21 11 59](https://user-images.githubusercontent.com/77174844/140662044-b66efa22-f54f-41f7-a5c3-16beb23c175b.png)
This is completely redundant in my opinion. There should be a way to prevent certain blocks from rendering.

I also think that list items should not start from zero, even between functions.
I could be wrong though.
![Screen Shot 2021-11-07 at 21 21 23](https://user-images.githubusercontent.com/77174844/140662345-b07c4469-08e3-4aff-8ebd-3a78c69a3409.png)

**Comment by mk** [comment]
Agree that hiding some or all code blocks initially (with the ability to expand them) is useful. We'll look into that.

Regarding the numbering of markdown lists, we're using [markdown-it](https://github.com/markdown-it/markdown-it) which implements [CommonMark](https://spec.commonmark.org/0.30/#list-items) and [trying it](https://spec.commonmark.org/dingus/?text=2.%20the%20function) looks like you're correct that this should be `2.`
<img width="1137" alt="CleanShot 2021-11-08 at 08 49 07@2x" src="https://user-images.githubusercontent.com/1187/140703434-431c20a5-f577-4308-a678-bbf441d5dea8.png">
:

The `start` attribute does get set correctly by Clerk but seems or css is overwriting it?
<img width="1253" alt="CleanShot 2021-11-08 at 08 51 11@2x" src="https://user-images.githubusercontent.com/1187/140703612-8a5172e2-4dca-4fb2-8149-2d01619e5b97.png">

**Comment by wildwestrom** [comment]
It seems like these styles conflict each other.
```css
.viewer-markdown ol {
    counter-reset: ol-counter;
    list-style: none;
}
.list-inside {
    list-style-position: inside;
}
```
`.viewer-markdown ol` takes precedence due to specificity, therefore `list-style` will be `none`.

**Comment by mk** [comment]
@wildwestrom yes, thanks! We addressed the ordered lists offset in #17.

**Comment by wildwestrom** [comment]
Should I close this then?

**Comment by mk** [comment]
We’ve now implemented controlling code cell & result visibility in https://github.com/nextjournal/clerk/commit/a6ee5c71f7975fdca055d1bb701c9ed566da700d. Thanks again for these reports!
