### ISSUE TITLE
Clerk Dash?

### ISSUE THREAD

**Issue by den1k** [nextjournal/clerk#133]
The notebook format is nice and pairs well with the linear model of code files but large notebooks also lead to a lot of scrolling. When the end-user is non technical code viewers are a distraction and the narrow width of the notebook also doesn't make use of available screen real estate. So I'm wondering: what if clerk had a viewers-only (all but code and comment based markdown) dashboard layout?

The dashboard layout could be specified on a code file as namespace metadata, including the format, e.g. number of grid columns or flex model. Using metadata individual viewers can then specify their placement.

Files could potentially be viewed either as a dashboard or regular notebook.

**Comment by jackrusher** [comment]
There are some features shipping in the coming weeks that should meet the goals stated in the issue. :)

**Comment by mk** [comment]
The feature Jack was mentioning landed in main with 133c32c608078ab8cc5d90b3eb762be2b8556791. If you're adventurous, do give it a spin or wait for us to document things better.

**Comment by den1k** [comment]
Excited to try and will do so ASAP (busy this week). Feel free to close or close upon docs landing.

**Comment by mk** [comment]
@den1k Let me know if the commit above serves your needs. I plan to take a closer look at your other PR next week, sorry about the delay here.

**Comment by den1k** [comment]
Will do asap!
