### ISSUE TITLE
`clerk/expand-paths` not working on windows

### ISSUE THREAD

**Issue by AndreasS2501** [nextjournal/clerk#141]
Thank you for creating clerk!

The static site generation fails in windows, tracking down the issue with martin resolved in finding this: 
```clojure
(clerk/expand-paths ["notebooks\\rule_30.clj"])
;; => []
```

Martin remarked:
"wondering if the `fs/glob` is a problem https://github.com/nextjournal/clerk/blob/main/src/nextjournal/clerk.clj#L457
[clerk.clj](https://github.com/nextjournal/clerk/blob/main/src/nextjournal/clerk.clj)"

**Comment by borkdude** [comment]
@mk Do you want me to take a look next week?

**Comment by mk** [comment]
@borkdude yes, please.

@AndreasS2501 I've updated the issue to be just about the `expand-paths` and created #142 about the links.

**Comment by AndreasS2501** [comment]
Thank you @mk

**Comment by borkdude** [comment]
PR #143 should fix this.

**Comment by borkdude** [comment]
@AndreasS2501 You should be able to test this by including `babashka/fs {:mvn/version "0.1.5"}` in your dependencies.
