### ISSUE TITLE
BYOServer – clerk as middleware

### ISSUE THREAD

**Issue by den1k** [nextjournal/clerk#148]
I'm looking into adding clerk to a prod instance and would like to place it under a specified route behind auth in my existing server setup (ring-compatible). Have you considered providing middleware/hooks instead of the standalone server to make this possible w/ clerk?

**Comment by den1k** [comment]
actually, this might already be possible by putting 

https://github.com/nextjournal/clerk/blob/main/src/nextjournal/clerk/webserver.clj#L60-L77

under a route. will try this

**Comment by den1k** [comment]
okay, got everything to work besides the reload over the websocket. I believe the culprit is in the route being hardcoded here

https://github.com/nextjournal/clerk/blob/de7ffa0906a308552cba029bb094a3422161e926/src/nextjournal/clerk/view.clj#L45-L48

**Comment by mk** [comment]
> I'm looking into adding clerk to a prod instance and would like to place it under a specified route behind auth in my existing server setup (ring-compatible).

Nice, this is something we want as well so I'm certainly up for figuring out what knobs we need to provide to make this easier. 

> To make an arbitrary starting route possible I wonder if `_blob` should be at the end of the path param, e.g. `domain.com/<my/clerk/route>/noteboook_xyz/_blob` so that one handler provided by clerk can manage all the routes.

Wondering if it would be enough if we allowed to support an optional `:path-prefix` for Clerk urls?

**Comment by den1k** [comment]
Great! It seems very straightforward unless I'm missing something.

> Wondering if it would be enough if we allowed to support an optional :path-prefix for Clerk urls?

that should work as long as blobs are also prefixed with it, e.g. `example.com/admin/clerk/_blob...`

**Comment by mk** [comment]
Since we're lacking a standard for websockets in Clojure I don't see a reasoable way to provide an easy solution that works with a variety of servers. Instead of Clerk providing our own middleware, we want to flesh out the [Clerk Dashboard example](https://github.com/nextjournal/clerkboard) more.
