### ISSUE TITLE
Unfolding long lists in `clerk/table` no longer works in latest version

### ISSUE THREAD

**Issue by rynkowsg** [nextjournal/clerk#153]
With an upgrade from 0.6.387 to 0.7.418 unfolding long lists stopped working.
The button "X more..." is there, but doesn't do anything.
Tested on both Firefox and Chrome.

**Comment by mk** [comment]
Hi, thanks for the report. We recently came across this regression as well and it's one my list of things to fix as part of a simplification of the viewer api that's currently happening in #152.
