### ISSUE TITLE
Remote REPL affordances

### ISSUE THREAD

**Issue by robert-stuttaford** [nextjournal/clerk#168]
As with https://github.com/nextjournal/clerk/issues/148 from [@den1k](https://github.com/den1k), we'd also like to be able to ship Clerk notebooks to production, and host them under a sub-route.

However, we'd also like to be able to modify those notebooks while they are there.

It seems that the loading process currently assumes access to a file. Could it instead be made capable of loading source directly from a string, which, by default, comes from a file?

Then we could write suitable code in Emacs or Joyride to automate the process of copying the current buffer's source and issuing a call to this string-based API with it, via the connected REPL.

**Comment by mk** [comment]
This is now possible (in `v0.11.603`) and newer by using a `java.io.StringReader`:
```clojure
(nextjournal.clerk/show! (java.io.StringReader. \";; # Notebook from String 👋\n(+ 41 1)\"))
```

With an example in the docstring: https://github.com/nextjournal/clerk/blob/549b581eff7692a6ed0ae676370265ba12708489/src/nextjournal/clerk.clj#L32
