### ISSUE TITLE
Remote clerk

### ISSUE THREAD

**Issue by den1k** [nextjournal/clerk#18]
In order to collect insights from production services I'd like to have a local clerk process (or server) running that eval's on a remote machine. This is analogous to a remote REPL where I send code to eval to a remote machine and receive the results locally in my IDE.

Is this possible today with clerk? If not what needs to be done to enable this?

**Comment by jackrusher** [comment]
This is easy to do today, but in a slightly different way than you've described. Use (for example) Emacs's `tramp` to start a REPL on whatever machine you want to use for computation and SSL port forwarding to connect your local browser to the remote Clerk.

**Comment by den1k** [comment]
Makes sense. That would require to have the clerk dep on the production instance, right? Is there a way to avoid that? E.g. eval remote but let clerk handle output locally?

**Comment by mk** [comment]
> That would require to have the clerk dep on the production instance, right? Is there a way to avoid that?

Why would you want to avoid that? It's a fine dep after all, isn't it? ;)

**Comment by mk** [comment]
In all seriousness I don't see how the dep is an issue on a box you're trying to use for heavy compute and if you want to use Clerk for compute with it's caching mechanism it will require deps like nippy, tools.analyzer etc.

What is possible is sharing the Clerk cache (defaults to `.cache` in your project dir via some shared fs as to not have to rerun expensive computations. This will work across runtime restarts and across machines.

**Comment by den1k** [comment]
Clerk is a fine dep! And I just remembered the original issue I had about using Clerk remotely. It uses a file-watcher and I can't make (or at least persist/commit to source control) new files on prod since the process is packaged up in a jar or runs through docker. So the watcher would have to run locally, where the file-system is and send changes to remote.

Can clerk pick up changes off my local file-system while evaluating through a remote process?

**Comment by jackrusher** [comment]
You don't need to use the file watcher. You can manually view namespaces with `show!` (in which case I recommend binding a key to call call `show!` via a Clerk-connected NREPL sessions whenever you need it). :)

**Comment by den1k** [comment]
Wonderful! Will try that. Closing for now.
