### ISSUE TITLE
Changing ::clerk/width does not report spec failures for invalid values

### ISSUE THREAD

**Issue by dgtized** [nextjournal/clerk#217]
Following through in the workshop, in https://github.com/nextjournal/clerk-demo/blob/master/workshop/exercises/ex_2_table_viewer.clj#L45:

changing `::clerk/width :full` to `::clerk/width :foo` does not report an error for invalid values .

In contrast, invalid values for `:code` in `::clerk/visibility {:code :fold}` report spec failures on invalid states.

Thanks!

**Comment by mk** [comment]
Closed by #294.
