### ISSUE TITLE
Feature request: `assert` for notebooks

### ISSUE THREAD

**Issue by mathpunk** [nextjournal/clerk#233]
This is surely something that one could write oneself, but I'm not the one :)

I was checking to see if some old poorly maintained code worked, so I wrote an assert statement about what should happen. The assertion failed, and Clerk shows that there was an exception and displays the stacktrace. What if instead there were a function (`demonstrate`? `clerk/assert`?) that turns the block failure red without affecting the rest of the view?

**Comment by jeroenvandijk** [comment]
@mathpunk Maybe the following macro is useful to you

```clojure
(defmacro test [expression & [message]]
  (let [msg (or message (pr-str expression))
        success-msg (str "✅ " msg)
        error-msg (str "❌ " msg " ;=> ")]
    `(try 
        (let [ret# ~expression]
          (if ret#
            ~success-msg
            (str ~error-msg ret#)))
        (catch Throwable ex#
          (str ~error-msg "Error: " (ex-message ex#))))))
```

`(test (= 1 1))` gives `"✅ (= 1 1)"`
`(test (= 1 2))` gives `"❌ (= 1 2) ;=> false"`
`(test (/ 1 0))` gives `"❌ (/ 1 0) ;=> Error: Divide by zero"`

**Comment by mathpunk** [comment]
Super cool, thank you!

**Comment by mk** [comment]
Nice, you can also conditionalise it to only do something in Clerk, see 
https://github.com/nextjournal/clerk/blob/234bee627353d6dca1050019fa00cafbbd0051f5/src/nextjournal/clerk.clj#L331-L336

**Comment by mk** [comment]
I'd love to see folks experiment with ideas like this and report back. Think it should happen in user land for the time being and not sure if should be part of Clerk however.

One thing we've played with around tests is a Clerk Kaocha test runner: https://github.com/nextjournal/clerk-kaocha

So please do report back (on slack or in a discussion here) your experiments & experiences but going to close this issue as I'd prefer to use other channels for feature requests that still need design work.
