### ISSUE TITLE
Misleading error when sci-context inspect fails

### ISSUE THREAD

**Issue by zampino** [nextjournal/clerk#244]
Reproducible a.o. with 

```clj
(clerk/with-viewer {:render-fn '(fn [_] [nextjournal.clerk.render/inspect bang])}
  42)
```

Although not completely wrong, maybe we could report back the form inspected

<img width="841" alt="CleanShot 2022-10-26 at 17 15 54@2x" src="https://user-images.githubusercontent.com/1078464/198066273-dae21ab6-8c63-4b2b-a816-2da68b46a7a2.png">

**Comment by mk** [comment]
I see a much better error (in dev):
<img width="996" alt="Screenshot 2022-10-26 at 16 20 46" src="https://user-images.githubusercontent.com/1187/198067134-e2aaf7bb-0cb7-4954-bb19-45820082a733.png">

**Comment by zampino** [comment]
Strange, I see what you see once I reload the page.
