### ISSUE TITLE
(array) maps are presented as alphabetically sorted maps in Clerk

### ISSUE THREAD

**Issue by ikappaki** [nextjournal/clerk#251]
Hi,

 (array) maps are _presented_ as sorted arrays in Clerk which is a bit unexpected; The map order is something that the user can manipulate (e.g. [sorted-map-by](https://clojuredocs.org/clojure.core/sorted-map-by))  thus it can be left to the user to decide on the order. 

As chatted on the slack channel whether the map can maintain its order during the _presentation_ stage

>   [mkvlr](https://clojurians.slack.com/archives/C035GRLJEP8/p1667053440110889?thread_ts=1666991867.597469&cid=C035GRLJEP8)
> not yet possible but would be doable by conditionally calling ensure-sorted in https://github.com/nextjournal/clerk/blob/main/src/nextjournal/clerk/viewer.cljc#L1073
> [viewer.cljc](https://github.com/nextjournal/clerk/blob/main/src/nextjournal/clerk/viewer.cljc)
>                          (ensure-sorted xs)))
> 
> ...
> could be done via an attribute on the map-viewer

May I advocate that the default should *not* be to sort the map but perhaps left it to the user to decide what the want using the current clojure tooling (`sort-map-by`, `array-map` etc)? 

Can't think of case where we want to force presentation of maps to be sorted, but I'm sure it has been done like this for a reason :)

Thanks

**Comment by ikappaki** [comment]
> It's not hard to detect that a map is sorted, what's harder is to say if this sorting was intentional. Showing maps and sets with random key order is pretty confusing so I think the default of sorting it feels right.

Hi @mk,

I guess this comes down to a matter of opinion :) 

I think we would both agree that for at least the `sorted-map` and `sorted-set` cases, the intention is clear, the user has explicitly requested the elements to be sorted and I believe they should be displayed as such.

Similarly in the case of `hash-map` and `set` there is no ordering in the container and the application is left ot decide what to do, IMHO this is the only case that Clerk should be opinionated in what order to display the elements.

There is also the `array-map` case, which muds the waters a little bit, it can be either
1. Something that was created with `{ }` with less than 10 elements, or
2. Something that the user explicilty created with `array-map`. 

`array-map`  falls unders the `ordered` collection category other than `sorted`, i.e. the elements are in the order inserted into the collection. If it is created with `{}` then I guess it falls at the same bucket as `hash-map`, but in the second case, the user has explicitly requested that order and should be displayed as such. Ordering the latter for displaying purposes is as bad as ordering a vector. 

So, IMHO there are more cases that alphabetical orderning will ruin the experience rather than provide a sensible default. 

My use case where I come from is `array-map`/1 and 2.

> We should provide a way to opt out however, probably via an option on the map viewer.

Happy to look at this in case you are occupied with other things, even if argument above would have not persuaded you otherwise :)

Thanks

**Comment by mk** [comment]
@ikappaki Sorry for not getting back to you for so long. I plan to be more responsive going forward, time will tell if it will come true as planned (:

Not going to change the default behavior of sorting keys in maps but open to enabling an opt out. If you're still interested in taking a look at this, please open a new issue  and we can talk about the implementation there.
