### ISSUE TITLE
Enhacement req: Make collection elements expansion configurable

### ISSUE THREAD

**Issue by ikappaki** [nextjournal/clerk#256]
Currently, collections (such as maps) are displayed on a single line with a triangular "handle" next to each collection, so that the user can opt to expand their elements, e.g.

![image](https://user-images.githubusercontent.com/34983288/199345914-518fd769-c28e-4de1-9513-0668a047ebd8.png)

It is unintuitive and hard for a user to read such an output at first sight, unless it is small in size.

It would be much better if the author had the option to either set all collection or subcollections as expanded at start or programmatically select which ones are selective to be expanded.

E.g. the above collection would have look much nicer at first sight with some of  its elements expanded compared to the one liner

![image](https://user-images.githubusercontent.com/34983288/199346598-ddd68e22-1ef7-49d5-a965-19b531752c64.png)

Would it be straighforward to provide such an option or are there technical challenges that need to be addressed first?

Thanks

**Comment by mk** [comment]
This is reasonable. We started working on auto-expanding data structures so the shape becomes more visible in #186, @joe-loco we should pick that up again. We should also add the ability to control the expansion programmatically.

**Comment by joe-loco** [comment]
With https://github.com/nextjournal/clerk/commit/e26cde9a30f1d0e2767759736f5ba12860ec40e1 it’s now possible to set auto-expanding results either for the entire ns:
```clj
(ns test
  {:nextjournal.clerk/auto-expand-results? true}
  (:require [clojure.string :as str]))
```
… or for a single result:
```clj
^{::clerk/opts {:auto-expand-results? true}}
(map range (range 30))
```

Mind that the heuristics for auto-expansion are currently simplistic and based on content length so there will be cases (e.g. for custom viewers) where this will work sub-optimal. We will likely make this based on measured element sizes in the future.

**Comment by ikappaki** [comment]
Thanks @joe-loco! I've tested this to work as expected with maps of various widths and depths.

I don't have a need the programmatic selection of nodes expansion at the moment, but it should certainly be a good addition to Clerk's arsenal. Are you also looking into this as well or shall this request only address the blanket auto-expansion of a container and thus be closed as completed?

**Comment by mk** [comment]
@ikappaki I think the path forward is using & testing the auto expansion more and reporting issues with it. Once we've tackled issues and tested it well in practice we might consider changing the default to auto-expand. 

Then we will hopefully learn if the need for more fine-grained control still exists. Going to close this issue and follow-up can happen in a discussion.
