### ISSUE TITLE
Tapping status bar doesn't scroll to top on iOS (safari, brave)

### ISSUE THREAD

**Issue by sritchie** [nextjournal/clerk#267]
On Clerk pages, something seems to be disabling the default behavior on iOS of "scroll to top when you tap the status bar".

Maybe related: on https://mentat-collective.github.io/mathlive.cljs/, when I click on the textarea on the bottom of the page, the page scrolls up to make room for the keyboard. This does NOT happen when I click the `Mathfield`, which brings up a virtual keyboard.

**Comment by sritchie** [comment]
I believe this is still an issue...

**Comment by mk** [comment]
We've been able to verify this with clerk-demo on v0.12.707 but it has since been fixed with 0bf24372b0fed5be6bf01ffb7c04b2e254526077. If you switch to a more recent sha this should be gone.

**Comment by sritchie** [comment]
Confirmed, thank you!
