### ISSUE TITLE
Watcher does not refresh file on change event on OS X

### ISSUE THREAD

**Issue by ikappaki** [nextjournal/clerk#27]
Hi, 

there appears to be a recent issue on OS X that watcher fails to load file after it has been modified.

to reproduce

1. Bring up the REPL and watch the `notebooks` folder
```clojure
(require '[nextjournal.clerk :as clerk])
(clerk/serve! {:watch-paths ["notebooks"]})
```
2. Open `http://localhost:7777`. and back at the REPL do
```clojure
(clerk/show! "notebooks/hello.clj")
```
3. The `hello.clj` should be shown at the browser.
4.  Add something to the `hello.clj` file and save it.
4. The page should refresh with the addition, but nothing happens.

PR to follow.

**Comment by mk** [comment]
Closed with 8ad88630f746f1a9ff3ac314f5528c2d25c42583.
