### ISSUE TITLE
Can't turn eliding off for tables 

### ISSUE THREAD

**Issue by ikappaki** [nextjournal/clerk#292]
Hi,

I can't seem to be able to turn elision off for clerk tables by following the instructions from [the book of clerk elision section](https://book.clerk.vision/#%F0%9F%94%93_elisions).

I  would have expected the eliding instructions to work for all viewers.

To reproduce
1. Create a notebook to display a table with 25 rows using `viewers-without-lazy-loading`, and also include the same table but display as a map with 25 entries. 
```clojure
(ns table-pagination
  (:require [nextjournal.clerk :as clerk]
            [nextjournal.clerk.viewer :as v]
            ))

(def without-pagination
  {:page-size #(dissoc % :page-size)})

(def viewers-without-lazy-loading
  (v/update-viewers v/default-viewers without-pagination))


^{::clerk/viewers viewers-without-lazy-loading
  ::clerk/viewer clerk/table
  }
(vec
 (repeat 25 {:1 1 :2 2}))

^{::clerk/viewers viewers-without-lazy-loading
  }
(vec
 (repeat 25 {:1 1 :2 2}))
```
2. `show!` notebook on the browser. Notice how the table is elided, while the map is not (i.e. the eliding is turned off only in the map viewer)
![image](https://user-images.githubusercontent.com/34983288/203163086-301e047e-69a6-485d-8071-f92667b4b90b.png)

Thanks

**Comment by zampino** [comment]
Hi @ikappaki, table viewers are not present in the default ones by default, [they're injected as child viewers by the table viewer when a value is being presented](https://github.com/nextjournal/clerk/blob/c44340790891384447ecdf4149abb4043c3c095c/src/nextjournal/clerk/viewer.cljc#L768). To have your example work you could do:

```clojure
(defn update-child-viewers [viewer f]
  (update viewer :transform-fn (fn [trfn] (comp #(update % :nextjournal/viewers f) trfn))))

(def unpaginated-table
  (update-child-viewers v/table-viewer (fn [vs] (v/update-viewers vs {:page-size #(dissoc % :page-size)}))))

^{::clerk/viewer unpaginated-table}
(vec (repeat 100 {:a 1 :b 2}))

```

**Comment by ikappaki** [comment]
Hi @zampino,

It works, thanks.

Is this something that should go into the book of clerk in the eliding section? 

IMHO, from a user's perspective, turning elidig off is such a fundamental task that clerk either an API provided to do so or a metadata option.

**Comment by behrica** [comment]
Maybe the same as #313

**Comment by mk** [comment]
I've created #406 to track this so I'm closing this.
