### ISSUE TITLE
Multiviewer notebook example ostensibly broken

### ISSUE THREAD

**Issue by lvh** [nextjournal/clerk#297]
(FWIW I'm somewhat confused between the purpose of the `notebooks` dir in this repo and the `clerk-demo` repo. Both seem demo-y? Fair warning: I've pretty much just seen the demo, I don't really understand what's going on, I'm sure my question is gonna be a bit silly :-))

I ran clerk like this: 

```
clj -A:demo    
```

Then loaded clerk and started serving:

```
user=> (require '[nextjournal.clerk :as clerk])
nil
user=> (clerk/serve! {:watch-paths ["notebooks" "src"] :show-filter-fn #(clojure.string/starts-with? % "notebooks")})
nil
```

Then loaded the multiviewer:

```
(clerk/show! "notebooks/multiviewer.clj")
```

I don't know what to expect but I'm guessing it's not the errors I saw. I saved this as a PDF, I dunno if there are other/better export mechanisms available.

[multiviewer-export.pdf](https://github.com/nextjournal/clerk/files/10097202/multiviewer-export.pdf)

**Comment by mk** [comment]
Thanks for the report, the attached commit fixes the multiviewer notebook.

> FWIW I'm somewhat confused between the purpose of the notebooks dir in this repo and the clerk-demo repo. Both seem demo-y? 

There's indeed quite a bit of overlap. We're currently using the notebooks in the Clerk repo more a development aid / test suite. We build a static app bundle like [this one](https://snapshots.nextjournal.com/clerk/build/28aa8a82581b9c63204df8c9803be2a9d75e5f61/index.html) on every commit and have tests that make sure they don't break. The multiviewer wasn't included here so we missed this regression. I added it in 81151bae1c638e449a5e639599df6436d8aa6d2f.

For users we recommend the demo repo. We'll do a Clerk release soon and clerk-demo will then be updated as well (currently the `bump-clerk` branch is using the latest clerk from `main`).

**Comment by lvh** [comment]
FYI depending on how much you want people to use the notebooks, I'd be happy to add my `clj -M:nextjournal/clerk nextjournal.clerk/serve! --watch-paths notebooks --port 7777 --browse` + `touch notebooks/whatever.clj` to the README :)
