### ISSUE TITLE
Multiline strings messing up rendering

### ISSUE THREAD

**Issue by emlyn** [nextjournal/clerk#306]
I have a multiline string in a var definition: [here](https://github.com/emlyn/advent-of-clerk/blob/b5d0f8f1c7c6694c17927ac43fcaebd532234597/src/advent_of_clerk/day_01.clj#L15-L29), that looks like:
```Clojure
(def ex
  (process "1000
2000
3000

4000

5000
6000

7000
8000
9000

10000"))
```

When rendered, most of the string (in the code) is repeated twice ([Clerk garden](https://github.clerk.garden/emlyn/advent-of-clerk/commit/b5d0f8f1c7c6694c17927ac43fcaebd532234597/src/advent_of_clerk/day_01.html)), like this:
<img width="878" alt="image" src="https://user-images.githubusercontent.com/405237/205304065-de69107c-fc90-4146-a413-8c8f0500c3fb.png">

**Comment by emlyn** [comment]
I've just noticed something similar on the Clerk introduction page [here](https://github.clerk.garden/nextjournal/clerk-demo/commit/3ccf0697a44908458d13485fbaf2ff680f7f25de/notebooks/introduction.html#🧮_tex): in the TeX code block, the string content is repeated twice, once in black and again in red. Maybe I'm missing something and it's supposed to be like this?

**Comment by mk** [comment]
@emlyn thanks for the report, nice catch. Looks like this might be a regression introduced in #275.
