### ISSUE TITLE
Invalid def/defn form causes silent failure

### ISSUE THREAD

**Issue by taylorwood** [nextjournal/clerk#307]
I've been playing with Clerk this week, great project!

I had this bad form in my notebook and noticed what seems like a silent failure:
```clojure
(def foo []
  'bar)
```
(It was supposed to be `defn`.)

This seems to also break the file watcher but I don't see any error log outputs in console or elsewhere.

Workaround: remove the form and restart the server.

**Comment by mk** [comment]
@taylorwood thanks for the report, the attached patch should fix the issue you were seeing.
