### ISSUE TITLE
Fold multiple code cells together?

### ISSUE THREAD

**Issue by T045T** [nextjournal/clerk#309]
Sometimes, I want to hide a whole block of `def`s and `defn`s, so a reader can look at the implementation of something only if they care enough (the motivating use case is me writing a custom viewer that has some helper functions).

Is there a way to do this in Clerk today? If not, should there be?

It might just be that I'm "holding Clojure wrong", as it were, so if there's a more idiomatic way to write code like the below (this is heavily simplified so that it's a single expression in the first place, please let me know :)

```clojure

(def svg-width 100)
(def svg-height 50)

(defn int->svg [x]
  [:text (str x)])
(defn make-svg [my-data]
  [:svn {:width svg-width :height svg-height} (map int->svg my-data)]
```

**Comment by mk** [comment]
I’ve used a `do` block to do this. Let me know if you feel this works sufficiently well.

**Comment by T045T** [comment]
That's exactly what i was looking for, thanks!
