### ISSUE TITLE
`serve!` is not "finished" when returning

### ISSUE THREAD

**Issue by behrica** [nextjournal/clerk#311]
The code below needs teh sleep after `serve!` , if not things break.
The tap-inspector will not start
Maybe we could avoid this.

```clojure
(do
(require '[nextjournal.clerk :as clerk])
(clerk/serve! {:browse true})
(Thread/sleep 1000)
(nextjournal.clerk/show! 'nextjournal.clerk.tap)
)
```

**Comment by mk** [comment]
> if not things break.

Can you say how or what breaks?

**Comment by behrica** [comment]
Firtsly, id does not start the tap viwer.
So running this after repl starts:

```clojure
(do
(require '[nextjournal.clerk :as clerk])
(clerk/serve! {:browse true})
;;;(Thread/sleep 1000)
(nextjournal.clerk/show! 'nextjournal.clerk.tap)
)
```
Does not start the tap viewer:
![image](https://user-images.githubusercontent.com/127361/205501417-e36414e8-68b2-4c6d-8593-5bb7174d5129.png)

Running it "later", after the above code finishes:

```
(nextjournal.clerk/show! 'nextjournal.clerk.tap)
```
does not start it neither (the browser does not show Tap Inspector)  . Bit I see alreday ouput of it:

```
Clerk evaluated 'file:/home/carsten/.gitlibs/libs/io.github.nextjournal/clerk/68493a089aaade404b4f0f5e551b4bdafbcbf182/src/nextjournal/clerk/tap.clj' in 218.621125ms.

```

So  tap inspector cannot be "started anymore" but is "neither full running"

**Comment by behrica** [comment]
If I do the above code by hand, one line after the other, then it works. (therefore the 'sleep' makes it work)

**Comment by behrica** [comment]
I think "(clerk/show! .... )" brings it back to live.

**Comment by mk** [comment]
I've tried this by adding the forms to `user.clj` on the clerk-demo project and it works all fine

If you'd like to avoid seeing the welcome screen you can also reverse the oder of `show!` and `serve!`:
```clojure
(require '[nextjournal.clerk :as clerk])
(clerk/show! 'nextjournal.clerk.tap)
(clerk/serve! {:browse true})
```

If the issue persists for you, please reopen with a repro I can run.
