### ISSUE TITLE
Spaces are missing in output strings

### ISSUE THREAD

**Issue by emlyn** [nextjournal/clerk#314]
If I have a string with any leading spaces, or multiple consecutive spaces, they are removed when showing the output. For example, this:
```clojure
;; A string with spaces:
"    hello     there     "
```
It is rendered as:
<img width="271" alt="image" src="https://user-images.githubusercontent.com/405237/205626880-62ca717e-e52a-47e3-b6f7-18bc7839040b.png">
The leading spaces are removed, and all groups of more than one space are reduced to a single space.

I'm not sure if this is related to #306, but it feels different, so I opened a separate issue.

**Comment by emlyn** [comment]
Also, if I select and copy the output string, it has a newline character at the start.

**Comment by emlyn** [comment]
I just checked with the latest version with #317 merged, and this is still happening.

**Comment by zampino** [comment]
@emlyn. Thank you for reporting this! Should be fixed with #319.
