### ISSUE TITLE
Feature request: capture stdout

### ISSUE THREAD

**Issue by emlyn** [nextjournal/clerk#316]
It would be nice if standard output (and possibly standard error too) could be captured and (optionally?) displayed after each cell. It would help for example with println debugging.

**Comment by jackrusher** [comment]
This is not as sensible as it appears at first glance. All code in all threads of the JVM share a single mutable stream for output (and another for error), so there's no good way to make sure you only get the output generated by a given cell in the "output" area of that cell. The easy workaround for this when you want a serial collection of events from a function is to create a a sequence in an `atom` and `conj` onto it from the function you're debugging.

**Comment by emlyn** [comment]
I've been thinking about this a bit more, and while your answer makes sense, it would still be nice to have an easy way to quickly get some debugging output from inside function calls, without having to set up an atom specially (and then delete it later).
Instead of trying to capture standard output, maybe Clerk could provide its own function to log some text that would be displayed alongside the cell output.
It could even be a reader macro, along the lines of [spyscope](https://github.com/dgrnbrg/spyscope). This would make it even easier to insert in front of a form, and it could also capture much richer information, like the source form, the evaluated value and type, and maybe even the execution time for basic benchmarking.

**Comment by jackrusher** [comment]
We have some more sophisticated evaluation inspection/debugging stuff on the roadmap, but it'll be some months before that stuff is ready for end users. In the meanwhile, you can use `tap>` to do similar things to Spyscope.
