### ISSUE TITLE
Missing leading whitespace in HTML

### ISSUE THREAD

**Issue by a1exsh** [nextjournal/clerk#321]
Input:
https://github.com/a1exsh/advent-of-clerk/blob/2c6a3f95e54da64400db614988bfceeccda63f21/src/advent_of_clerk/day_05.clj#L8-L16

## `io.github.nextjournal/clerk {:mvn/version "0.11.603"}`

```clj
(def example "    [D]    
[N] [C]    
[Z] [M] [P]
 1   2   3 

move 1 from 2 to 1
move 3 from 1 to 3
move 2 from 2 to 1
move 1 from 1 to 2")
```

Collapsed:
`"[D] ↩︎[N] [C] ↩︎[Z] [M] [P]↩︎ 1 2 3 ↩︎↩︎move 1 from 2 to 1↩︎move 3 from 44 more…"`

Expanded:
```
"
[D]
[N] [C]
[Z] [M] [P]
1 2 3

move 1 from 2 to 1
move 3 from 44 more…"
```

**The leading spaces are missing!**

## `io.github.nextjournal/clerk {:mvn/version "0.12.699"}`

```clj
(def example "    [D]    
[N] [C]    
[Z] [M] [P]
 1   2   3 
move 1 from 2 to 1
move 3 from 1 to 3
move 2 from 2 to 1
    [D]    
[N] [C]    
[Z] [M] [P]
 1   2   3 

move 1 from 2 to 1
move 3 from 1 to 3
move 2 from 2 to 1
move 1 from 1 to 2")
```
**Note the incorrect duplicate string!**

The collapsed and expanded output forms are not different from the older version.

**Comment by a1exsh** [comment]
Rendered with `0.12.699`: https://github.clerk.garden/a1exsh/advent-of-clerk/commit/2c6a3f95e54da64400db614988bfceeccda63f21/src/advent_of_clerk/day_05.html

**Comment by mk** [comment]
I believe this is a duplicate of #314. Can you try if 51b28898a3d540ea75d79635402498a2948f6baa fixes the issue for you?

**Comment by a1exsh** [comment]
Yeah, looks like a duplicate — somehow I didn't find anything similar before opening the issue.

I want to try, but getting this error: `Error building classpath. Library io.github.nextjournal/clerk has missing :sha in coordinate.`

Is my Clojure too old (`1.10.3`)?

**Comment by mk** [comment]
@a1exsh it should like you need to upgrade your Clojure CLI, here's the output of mine
```sh
$ clj --version
Clojure CLI version 1.10.3.1040
```

What does yours say?

**Comment by mk** [comment]
Indeed that is too old, you have https://clojure.org/releases/tools#v1.10.3.855 whereas you need https://clojure.org/releases/tools#v1.10.3.933 or later which added support for inferred `:git/url`s. In case you don't want to upgrade, you can also try specifying `:git/url` `"https://github.com/nextjournal/clerk"` manually.

**Comment by a1exsh** [comment]
@mk yay, this worked:
```edn
        io.github.nextjournal/clerk
        {:git/url "https://github.com/nextjournal/clerk"
         :sha #_"51b2889" "51b28898a3d540ea75d79635402498a2948f6baa"}
```

Closing the issue — thanks a ton!
