### ISSUE TITLE
Hanging on some infinite sequences

### ISSUE THREAD

**Issue by emlyn** [nextjournal/clerk#325]
If I have an infinite sequence like `(range)`, Clerk handles it fine and displays:
<img width="606" alt="image" src="https://user-images.githubusercontent.com/405237/206432979-bccfc0bd-eba8-4f60-83f0-a2b015811bcb.png">

However, if I do something like `(map inc (range))`, Clerk will hang, and even if I remove the offending line, it doesn't come back to life.

It's difficult to interrupt the process - typing Ctrl-C multiple times sometimes kills it after a while, but other times does nothing. Sometimes it prints:
`OpenJDK 64-Bit Server VM warning: Exception java.lang.OutOfMemoryError occurred dispatching signal SIGINT to handler- the VM may need to be forcibly terminated`

And then if I forcibly terminate it with Ctrl-Z then `kill %1`, the next time I try to start it up, the port is unavailable:

`Port  7878  not available, server not started!`

**Comment by mk** [comment]
@emlyn @philomates thank you both!
