### ISSUE TITLE
Markdown headings don't have unique IDs

### ISSUE THREAD

**Issue by T045T** [nextjournal/clerk#330]
Quick repro:

```clj
;; # Time Travel: Solved
^{:nextjournal.clerk/toc true}
(ns time-travel
  "Where we're going, we don't need roads."
  (:require [nextjournal.clerk :as clerk]))

;; ## Introduction
;; Lorem ipsum et cetera.
;; ### Quantum Physics
;; Dolor sit and so on.

;; ## References
;; It's important to cite your references!
;; ### Quantum Physics
;; Particularly for quantum physics!
```

Using Clerk 0.12.699, this generates two identical `<h3>` tags with the ID "solving". The TOC contains two links, but understandably, my browser doesn't know which one refers to which `<h3>` and both links scroll to the first one.

Generating unique IDs would be ideal, but support for [custom heading IDs](https://www.markdownguide.org/extended-syntax/#heading-ids) might be easier and would allow me to solve this issue in "user-space".

**Comment by mk** [comment]
Thanks for the report, agree that this should be fixed with unique ids.
