### ISSUE TITLE
Confusing error when paths fed to builder are empty

### ISSUE THREAD

**Issue by zampino** [nextjournal/clerk#339]
This is thrown

```
Execution error (NullPointerException) at nextjournal.clerk.builder/build-static-app! (builder.clj:284).
Cannot invoke "clojure.lang.IFn.invoke(Object)" because "report_fn" is null
```

when calling `(builder/build-static-app! {:paths ["foo/**/*.clj"]})` against an empty glob `"foo/**/*.clj"`, also reproducible with `(builder/build-static-app! {:paths []})`.

**Comment by aviflat** [comment]
Possibly related: if I pass `:paths` with a single path — if the options map contains only `:paths` that works more or less fine. But if I _also_ specify `:index` then I get the same NPE.

As discussed [in Clojurians](https://clojurians.slack.com/archives/C035GRLJEP8/p1670952412217789?thread_ts=1670941431.180639&cid=C035GRLJEP8)

**Comment by kautsig** [comment]
Can reproduce the problem @aviflat described in `:mvn/version "0.12.707"`. If I understand the code correctly, the problem is that the `build-static-app!` function, which extracts `:keys` and *then* calls `process-build-opts` which sets the `:report-fn`.

```  clojure
(let [{:as opts :keys [download-cache-fn upload-cache-fn report-fn compile-css? expanded-paths error]}
        (try (process-build-opts (assoc opts :expand-paths? true))
             (catch Exception e
               {:error e}))
```

I am not sure how empty paths fix relate to this though.

**Comment by kautsig** [comment]
My previous comment is wrong. I failed to read the let binding correctly. I am still investigating the NPE.

**Comment by kautsig** [comment]
Ok, I got it.

`process-build-opts` threw an error, never setting `report-fn` at all.  Root cause was: 
```
`:index` must be string and point to existing file`.
```

No reason to reopen that, sorry for the noise.
