### ISSUE TITLE
use full qualified symbols in viewer selection

### ISSUE THREAD

**Issue by behrica** [nextjournal/clerk#341]
Just to not forget this.

Work was started here:
[Also support and resolve fully qualified symbols as viewers](https://github.com/nextjournal/clerk/commit/d292a2c4bc635e839a3feaf68e50aa42cd821d62)

It allows to do some nice editor integrations including interactive viewer selections with the tap-inspector.

**Comment by mk** [comment]
I think this is done. I've clarified the example usage in 38fb3e31c19ee288e4e51b8a09d5f34be07ca3d4. If you have further needs, let's discuss them on slack.
