### ISSUE TITLE
Does not scroll to relevant section when using anchor link

### ISSUE THREAD

**Issue by T045T** [nextjournal/clerk#343]
Say I have something like 

```clj
;; # My favorite algorithm: A*
```

The TOC link for this will look something like `https://nonsense.local:7777/test.html#my_favorite_algorithm:_a*`, but `:` and `*` both need to be URL-encoded.

**Comment by T045T** [comment]
Actually, never mind, the problem is something else: „Deep links“ to headings seem to not work at all :(

**Comment by mk** [comment]
@zampino has been working on links in #336. If I read his comments correctly that includes fixing deep linking.

**Comment by zampino** [comment]
> that includes fixing deep linking.

It didn't, but does now with ebf165bffdda6458143a2cdf88d0d709a0dbe0df and following commits.

With @joe-loco we shortly investigated why the browser's built-in behaviour wouldn't follow internal links, coldn't find a good reason yet, resorted to explicitely scroll when notebook view mounts ftm.
