### ISSUE TITLE
how to hide result from hidden form?

### ISSUE THREAD

**Issue by genmeblog** [nextjournal/clerk#35]
Having `^{:nextjournal.clerk/visibility #{:hide}}` or `^{:nextjournal.clerk/visibility #{:fold}}` the form is hidden/folded but still result of evaluating it is rendered (which is confusing). Is there any way to hide result as well?

**Comment by mk** [comment]
Hi @genmeblog, you can currently hide the result using the `clerk/hide-result` viewer, see
https://github.com/nextjournal/clerk/blob/d7b3e6602795b306bc75925fe70803db38fcfaa0/notebooks/visibility.clj#L22-L24

We're considering to make this accessible via metadata in the future https://github.com/nextjournal/clerk/pull/24#issuecomment-992206819

**Comment by genmeblog** [comment]
thanks for quick response!

**Comment by andres-moreno** [comment]
The `clerk/hide-result` gets confused if one uses a var:

`(clerk/hide-result (def blip (range 0 500)))`

produces an output cell with the specified range.
