### ISSUE TITLE
Failed to setup d3-graphviz

### ISSUE THREAD

**Issue by dainiusjocas** [nextjournal/clerk#353]
Clerk is amazing! I'm pleasantly surprised at what I can achieve with it.

However, I've tried to use [d3-graphviz](https://github.com/magjac/d3-graphviz) library in notebook in a similar fashion to the `mermaid` library but it didn't work.

I've investigated why the library failed and it seems that loading the `graphvizlib.wasm` is a problem. Can it be so that WASM is not supported?

My viewer:
```clojure
(def graphviz-viewer
  {:transform-fn clerk/mark-presented
   :render-fn    '(fn [value]
                    (v/html
                      (when value
                        [v/with-d3-require {:package ["d3-graphviz@4.5.0"]}
                         (fn [graphviz-package]
                           [:div#graphviz {:ref (fn [el]
                                                  (when el
                                                    (.renderDot (.graphviz graphviz-package "div#graphviz" {}) value)))}])])))})

(clerk/with-viewer graphviz-viewer "digraph {a -> b} ")
```

The browser console:
<img width="707" alt="Screenshot 2022-12-18 at 16 12 12" src="https://user-images.githubusercontent.com/230044/208303107-f60e488f-8ce9-4959-a4ce-2ae49023513b.png">

Deciphering magic words:
"00 61 73 6d" =>"\NULasm"
"3c 21 44 4f" => "<?DO"

**Comment by mk** [comment]
Sorry for taking forever to get back to you. There's no reason WASM shouldn't be supported but loading this can be a bit finicky. Looks like a new version of d3-graphviz out that loads fine as an ESM module:

```clojure
(ns viewers.d3-graphvis
  (:require [nextjournal.clerk.viewer :as-alias v]
            [nextjournal.clerk :as clerk]))

(def graphviz-viewer
  {:transform-fn clerk/mark-presented
   :render-fn    '(fn [value _]
                    [nextjournal.clerk.render/with-dynamic-import {:module "https://cdn.skypack.dev/d3-graphviz"}
                     (fn [graphviz-package]
                       [:div#graphviz {:ref (fn [el]
                                              (when el
                                                (.renderDot (.graphviz graphviz-package "div#graphviz" {}) value)))}])])})

(clerk/with-viewer graphviz-viewer "digraph {a -> b} ")
```

In action:
<img width="864" alt="Screen Shot 2023-02-06 at 09 48 55" src="https://user-images.githubusercontent.com/1187/216926314-8c406639-a0b2-429a-8ea7-622bffd88457.png">
