### ISSUE TITLE
cannot add to TOC dynamically

### ISSUE THREAD

**Issue by behrica** [nextjournal/clerk#355]
see here:

https://app.slack.com/client/T03RZGPFR/C035GRLJEP8/thread/C035GRLJEP8-1671377428.168149

**Comment by mk** [comment]
Could you please add a description instead of only linking to slack, thanks!

**Comment by behrica** [comment]
I would like to add items to the TOD dynamically, via code.
Either by

```
(clerk/md "### 123")  ;; on top level
```
or nested.

BMy use case is that I auto-generated larger hiccup , aand embedding / nesting of other clerk viewers is allreday working.
But contributing to TOC is missing.


Example is here:
https://scicloj.github.io/scicloj.ml-tutorials/userguide-models.html

My top level chapter are "static", but I would like to add 3.level TOC items to point directly to the models
The html for the model list is generated by code.

**Comment by mk** [comment]
Decided to not do this at this time because we want to be able to generate the ToC for a doc without needing to evaluate it. I'd recommend to generate the markdown or its intermediate representation programmatically and feeding that to Clerk instead.
