### ISSUE TITLE
code in markdown fences has different widths, could use Codemirror?

### ISSUE THREAD

**Issue by sritchie** [nextjournal/clerk#366]
Moved over from a Slack conversation:

I noticed that if embedded code blocks inside of a markdown code fence have different width than a code block… and maybe syntax highlighting is not working?

For example, on https://jsxgraph.mentat.org/ note the different widths between the code fence on top and clojure forms below:

<img width="976" alt="image" src="https://user-images.githubusercontent.com/69635/208903256-bd173fa4-4c97-408f-8a61-1b9e1e0dccbc.png">

Can we tune this at all?

Re codemirror:

@zampino noted "yeah, fenced or indented code blocks in markdown are rendered with the default code viewer (hence with clojure syntax) but with the width of prose. Now that we have stateless syntax highlighting we could try to load codemirror language support lazily at least for known languages."

**Comment by mk** [comment]
Let's try to make them look the same but have a `Code Listing: Clojure` label.
