### ISSUE TITLE
whole page scrolls horizontally on mobile

### ISSUE THREAD

**Issue by sritchie** [nextjournal/clerk#376]
On the latest clerk, the page is free to scroll horizontally; this lets me push the text out of focus by accident when trying to scroll vertically. It would be great if we could limit scrolling of the main page to vertical only.

**Comment by mk** [comment]
We failed to reproduce it. This can be caused by a viewer that breaks out of the main column. Please reopen with a repro if this is still an issue for you.

**Comment by joe-loco** [comment]
I was able to repro this with the Book of Clerk notebook. Markdown code fences with long lines are the culprit. Looking into a more comprehensive fix now.
