### ISSUE TITLE
Long-running code

### ISSUE THREAD

**Issue by emlyn** [nextjournal/clerk#380]
One issue I ran into when doing [advent-of-clerk](https://github.com/nextjournal/advent-of-clerk), was that sometimes I would save the file with code that ran for a long time (several minutes or more), and it would prevent rendering of the notebook, with no way to cancel it apart from killing and restarting the Clerk process.

It would be useful to have a timeout (maybe configurable with metadata?) to prevent the Clerk process getting stuck.

Even better, could the rendering and the code evaluation be in separate threads, and the notebook initially rendered without any results, then the results could gradually get filled in as they are calculated?

**Comment by mk** [comment]
I agree that the non-existent feedback isn't great for long-running cells.

Less sure about solving this with a timeout. I use `cider-interrupt` and it mostly works to abort a long-running computation, be it from `clerk-show` or not.

> Even better, could the rendering and the code evaluation be in separate threads, and the notebook initially rendered without any results, then the results could gradually get filled in as they are calculated?

Yes, this is something we've been thinking about.

**Comment by mk** [comment]
@emlyn the attached PR is a first stab at showing execution progress. The rendering doesn't happen in steps yet as I'd like to make incremental progress here. In case you get a chance to play with this, I'd be curious to hear how you like it.

**Comment by emlyn** [comment]
Thanks, that sounds really nice! I'll give it a try soon, hopefully this weekend.
