### ISSUE TITLE
Map inside Clerk table displays wierdly (`:mvn/version "0.12.707"`)

### ISSUE THREAD

**Issue by teodorlu** [nextjournal/clerk#390]
Hi!

When I render a map in a Clerk table, the viewer seems to choke. Strings look like symbols, and a closing `}` is missing.

Let me know if you want more details!

Teodor

```clojure
(clerk/table
 [{"password" "abc"
   "hash(password)" {:rainbowtable/password "6fee74066d6f9452b311669272b91809504534c5"}}
  {"password" "cat"
   "hash(password)" {:rainbowtable/password "9d989e8d27dc9e0ec3389fc855f142c3d40f0c50"}}])
```

![image](https://user-images.githubusercontent.com/5285452/213871286-88aff098-c28d-44bd-8cf8-d0485f812d8e.png)

![image](https://user-images.githubusercontent.com/5285452/213871378-b7ea55a7-e83a-4881-86fa-8667fc4519b4.png)

**Comment by mk** [comment]
Our parens rewriting is probably to blame for this. @zampino can you take a look here when you're back?

**Comment by mk** [comment]
@teodorlu see the attached fix, thanks for the report!

**Comment by teodorlu** [comment]
Perfect, thanks!
