### ISSUE TITLE
build! with glob for :paths pulls in cljs files

### ISSUE THREAD

**Issue by sritchie** [nextjournal/clerk#403]
Repro here: https://github.com/sritchie/clerk-repro

Given this `deps.edn`:

```clj
{:paths ["src"]
 :aliases
 {:nextjournal/clerk
  {:extra-deps
   {io.github.nextjournal/clerk
    {:git/sha "4180ed31c2864687a770f6d4f625303bd8e75437"}}
   :exec-fn nextjournal.clerk/build!
   :exec-args
   {:index "src/clerk_repro/notebook.clj"
    :paths ["src/**"]}}}}
```

and a `src` folder with `clerk_repro/{notebook.clj, test.cljs}`, `clerk/build!` is pulling in `test.cljs` and failing with this error:

```sh
[sritchie@wintermute ~/code/clj/clerk-repro (main)]$ clj -X:nextjournal/clerk
👷🏼 Clerk is building 3 notebooks…
🧐 Parsing… Done in 33.770ms. ✅
🔬 Analyzing… Done in 116.592ms. ✅
🔨 Building "src/clerk_repro/notebook.clj"… Done in 15.605ms. ✅
🔨 Building "src/clerk_repro/test.cljs"… Errored in 5.166ms. ❌
🔨 Building "src/clerk_repro/notebook.clj"… Done in 5.237ms. ✅
Syntax error (ExceptionInfo) compiling at (test.cljs:5:1).
Syntax error compiling at (src/clerk_repro/test.cljs:5:1).
No such namespace: js
```

I would have expected `build!` to ignore `cljs` files.

**Comment by sritchie** [comment]
I can solve it with `src/**.clj`; but I still would have expected that clerk would filter out any file types it can't handle? Thoughts?

**Comment by mk** [comment]
I'm not sure. Leaning towards making the glob more explicit in user land land use `src/**.clj`. Otherwise we lock out e.g. `.bb` and `.cljs` files that could actually run?

**Comment by sritchie** [comment]
Yeah, I think you're probably right! I'll adjust my glob, makes sense not to limit for the reasons you say.
