### ISSUE TITLE
Clerk double-builds notebooks from `:index`, `:paths`

### ISSUE THREAD

**Issue by sritchie** [nextjournal/clerk#405]
If a notebook is set as `:index`, but is also specified in `:paths` (or picked up by a glob like `src/**` in `:paths`, it's built twice:

```
[sritchie@wintermute ~/code/clj/clerk-repro (main)]$ clj -X:nextjournal/clerk
👷🏼 Clerk is building 2 notebooks…
🧐 Parsing… Done in 45.463ms. ✅
🔬 Analyzing… Done in 156.340ms. ✅
🔨 Building "src/clerk_repro/notebook.clj"… Done in 10.982ms. ✅
🔨 Building "src/clerk_repro/notebook.clj"… Done in 6.527ms. ✅
```

See https://github.com/sritchie/clerk-repro, 

```sh
clj -X:nextjournal/clerk
```

This is a cheap notebook so it doesn't matter, but for more expensive notebooks (like some of the physics simulations) this would be an issue.

**Comment by mk** [comment]
@sritchie good catch, fixed with 7222881.
