### ISSUE TITLE
MD text after math formula is not rendered

### ISSUE THREAD

**Issue by genmeblog** [nextjournal/clerk#427]
Markdown starting with math formula strips off the text after the formula

```clojure
;; renders properly
(clerk/md "text before $$\\sin(x)$$")
;; renders only sin(x)
(clerk/md "$$\\sin(x)$$ text after")
;; renders properly
(clerk/md "text before $$\\sin(x)$$ text after")
;; renders only delta
(clerk/md "$$\\delta$$ and $$\\alpha$$")
```

**Comment by genmeblog** [comment]
![image](https://user-images.githubusercontent.com/38646601/222130820-ae1e322d-dced-417d-9b1e-7f5ebeff6f28.png)

**Comment by zampino** [comment]
Hi @genmeblog thanks for reporting that. I believe the double dollar `$$` is actually intended to be parsed as a _block formula_ while the single dollar `$` is for _inline formulas_.

So these all render fine:

```clj
(clerk/md "text before $\\sin(x)$")

(clerk/md "$\\sin(x)$ text after")

(clerk/md "text before $\\sin(x)$ text after")

(clerk/md "$\\delta$ and $\\alpha$")
```

The _intended_ syntax for formulas would look like

```clj
(nextjournal.markdown/parse "This is $\\mathsf{inline}$ while this

$$\\int_a^b\\phi(t)dt$$ ignored

is a block formula.
") ;; =>

{:type :doc,
 :content [{:type :paragraph,
            :content [{:type :text, :text "This is "}
                      {:type :formula, :text "\\mathsf{inline}"}
                      {:type :text, :text " while this"}]}
           {:type :block-formula, :text "\\int_a^b\\phi(t)dt"}
           {:type :paragraph, :content [{:type :text, :text "is a block formula."}]}]}
```

Under the hood we're using the [TeXMath plugin for markdown-it](https://github.com/goessner/markdown-it-texmath#features) and the library treats a line starting with `$$` as a block.

If an expression surrounded by `$$` is preceded by other characters, then [we interpret it as an inline formula](https://github.com/nextjournal/markdown/blob/78f58b21a7efaec36a99d0b93f0db75830e8c1fa/src/nextjournal/markdown/parser.cljc#L572):

```clj
(nextjournal.markdown/parse "before $$\\int_a^b\\phi(t)dt$$ not ignored")

;; =>
{:type :doc,
 :content [{:type :paragraph,
            :content [{:type :text, :text "before "}
                      {:type :formula, :text "\\int_a^b\\phi(t)dt"}
                      {:type :text, :text " not ignored"}]}]}

```

**Comment by zampino** [comment]
I guess in the intention of the library, the token `math_inline_double` is intented for inline formulas rendered in display style as explained at the beginning of this section: https://www.overleaf.com/learn/latex/Display_style_in_math_mode#Overriding_default_mathematical_styles.

We might consider doing that as well.

**Comment by genmeblog** [comment]
Ah, got it. I was mislead by seeing rendered text in block formulas and thought it should work in both cases.
 
@zampino thanks a lot for explanation. I'm closing the issue.
