### ISSUE TITLE
Enable cherry as alternative evaluator in addition to SCI

### ISSUE THREAD

**Issue by borkdude** [nextjournal/clerk#441]
Preview is available in commit `ef3023e148a783228f193e4ed95f30e18544e7ae` in the cherry branch (other commits use local/roots, until I straighten stuff out more, I'll update the demo commits in this post). Start the `notebooks/cherry.clj` notebook and play around.

I'll use this issue to track any issues while working to a merge-worthy PR.

<img width="1212" alt="Screenshot 2023-03-21 at 17 11 02" src="https://user-images.githubusercontent.com/284934/226670469-a2e9b696-93dd-427c-b164-93d354b2a320.png">

[Preview notebook](https://snapshots.nextjournal.com/clerk/build/064b5b011e482492c166eb7a2f1070de3aac82d4/index.html#/notebooks/cherry.clj)

TODO:

- [x] try out @sritchie's performance intensive notebook: WIP https://github.com/borkdude/MathBox.cljs/commit/9126e19478d6a6bdb0079fba0a704ed37c23e2b5 (start with cider-jack-in + `user/serve`, then visit `heli.cljc` notebook)
- [x] fix tests in squint and cherry for the clerk-related branches
- [x] decide on API for :core-alias
- [x] how to deal with macros: API to register macros globally (`reagent.core/with-let`)

**Comment by sritchie** [comment]
I'm excited to see this!
