### ISSUE TITLE
Navigating to an anchor in the static generated HTML replaces all content with nil

### ISSUE THREAD

**Issue by holyjak** [nextjournal/clerk#449]
If I `build!` a static html file (in my case with `:bundle true`) then the headings will have IDs so that I can link to them. However, doing so breaks the page and it only displays `nil`.

Clerk v.: 56bb0fa5e4f21d70f3ac763dc13ad1ab28164d8d

**Comment by zampino** [comment]
This is not the case with latest clerk anymore, although linking to fragment _across_ documents in the bundled case need still to be supported.
