### ISSUE TITLE
`declare` should not show values

### ISSUE THREAD

**Issue by mk** [nextjournal/clerk#454]
<img width="536" alt="Screen Shot 2023-04-18 at 21 11 04" src="https://user-images.githubusercontent.com/1187/232880894-b1860b2c-b074-4048-837f-c69277b96ed7.png">

**Comment by zampino** [comment]
It's not only about showing values, but definitions of forward declarations are actually evaluated _before_ their dependents, making e.g this namespace showable in clerk, but not loadable by plain clojure

```clj
(ns scratch.debug
  (:require [nextjournal.clerk :as clerk]))

(declare delayed-def)

(inc delayed-def)

(def delayed-def 123)
```

 This has been reported by @sheluchin on [clojurians slack](https://clojurians.slack.com/archives/C035GRLJEP8/p1704039934053129) before.

**Comment by zampino** [comment]
>  definitions of forward declarations are actually evaluated before their dependents

this is actually related to the displayed values because we actually eval `(def delayed-def 123)` instead of `(declare delayed-def)`:

https://github.com/nextjournal/clerk/blob/cc5cf40f45afb50c7df51a81247920c64e798452/src/nextjournal/clerk/eval.clj#L168
