### ISSUE TITLE
Fragments and auto expand results

### ISSUE THREAD

**Issue by sh54** [nextjournal/clerk#465]
`:nextjournal.clerk/auto-expand-results?` seems to work differently for things rendered as a fragment.

Best illustrated with an example.

### ns settings

```
(ns parser
  {:nextjournal.clerk/visibility {:code :hide}
   :nextjournal.clerk/auto-expand-results? true}
  (:require [nextjournal.clerk :as clerk]))
```

### Notebook code

```
So the following:

;; ### Directly

(clerk/html
 [:div
  [:pre "The stuff to parse"]])

[:some-tree
 [:item [:text "hello "] [:text-bold "world"]]
 [:item [:text "hello "] [:text-bold "world"]]
 [:item [:text "hello "] [:text-bold "world"]]
 [:item [:text "hello "] [:text-bold "world"]]
 [:item [:text "hello "] [:text-bold "world"]]]

;; ### Using fragment

(clerk/fragment
 (clerk/html
  [:div
   [:pre "The stuff to parse"]])
 [:some-tree
  [:item [:text "hello "] [:text-bold "world"]]
  [:item [:text "hello "] [:text-bold "world"]]
  [:item [:text "hello "] [:text-bold "world"]]
  [:item [:text "hello "] [:text-bold "world"]]
  [:item [:text "hello "] [:text-bold "world"]]])
```

### Screenshot of initial render

<img width="787" alt="image" src="https://user-images.githubusercontent.com/906180/235342297-301bf34b-9aff-465d-9aa3-4cd571f7d7e4.png">

The first view of the tree looks great.

When placing the tree in a fragment then it seems the enclosing collection does not get expanded but the first found collection does get expanded.

I would expect both trees to render the same initially.

#### For context

I am trying to show some text that will be parsed and its resulting parse tree together. So I will make some function `parse` that returns something that results in those two things getting displayed in the notebook.

**Comment by mk** [comment]
Thanks for the report, hope we get around to fixing it in the coming days.
