### ISSUE TITLE
Visibility option for clerk metadata

### ISSUE THREAD

**Issue by yuhan0** [nextjournal/clerk#479]
The parts of the documentation dealing with metadata read quite confusingly, because the code it refers to has been stripped out during the rendering process:
<img width="787" alt="image" src="https://github.com/nextjournal/clerk/assets/22216124/9c13e1ce-1555-4f29-8f36-2393b9ffbf0d">
https://book.clerk.vision/#applying-viewers

The reader has to navigate to the source file (not an obvious/easy step) and search for the corresponding position to actually see the thing being referred to:
https://github.com/nextjournal/book-of-clerk/blob/c47477cb3ca72740de82c9fd3ddcb384f7c7eeb9/book.clj#L416

The problem, of course, is that the code block viewers implicitly assume that `::clerk`-namespaced metadata is irrelevant to the presented document, and strips them out. For some pedagogical purposes this is not the case, and writers may want to opt-in to displaying these metadata verbatim.

I propose an additional `:meta` key in the `:nextjournal.clerk/visibility` map, that defaults to `:hide`, and behaves in the same way as the current :code and :result keys - one could set it globally in the ns metadata, or locally per form, or toggle it using a top-level map literal.
```clj
^{::clerk/visibility {:meta :show}} 
(...)
```

The transform-fn for the code-block-viewer would then use this to decide whether to display `:text` or `:text-without-meta`. https://github.com/nextjournal/clerk/blob/a60cda1e4a7a8b8bfdb96b5c13756b2342644997/src/nextjournal/clerk/viewer.cljc#L964
I have a prototype of this working locally and would be happy to submit a PR. Thanks!

**Comment by mk** [comment]
Hi @yuhan0, thanks for the issue. I do think you're right and we should add an option to support showing the metadata. 

I wasn't immediately thinking of this in terms of visibility. If you hide the code cell, this option would never apply do anything.

Another possibility that comes to mind is an option on the code-block-viewer. I think this would require some changes to the viewer api as it currently does not expose the viewer inside it's transform-fn but this is something @zampino and I have been talking about. This makes it slightly less convenient to change but maybe more obvious what's happening?

**Comment by zampino** [comment]
What we can also do, is to tell the `code-block-viewer` to display the cell's code as is. 

```clj skip
(clerk/add-viewers! [(assoc viewer/code-block-viewer
                            :transform-fn (viewer/update-val :text))])
```

That would apply to all the code cells of the notebook as we don't have a mean to scope viewers to just a fraction of the document and we cannot hook onto the viewer for the code block on a per-cell basis.

**Comment by zampino** [comment]
@yuhan0 if you need a more targeted scope (e.g. using metatada) you can still do so by using the `:transform-fn` of your choice in combination with the `clerk/add-viewers!` call above.

**Comment by yuhan0** [comment]
I find that quite a strange solution - I don't have a good grasp of the library internals yet, but does it work on the principle that `with-viewer` takes an qualified symbol argument and searches down `!viewers` to find the first matching one by the `:name` key? 
So that call "shadows" the default code-block viewer by installing a new viewer at the start of the vector with the same name -  and this applies globally to all cells, even if the `(add-viewers!` call takes place at the end of the document.

To me it still seems like a `:visibility` setting - although @mk is right that according to my suggestion, the combination of `{:code :hide, :meta :show}` would be ill defined, unless we (reasonably) say that `:code` visibility always takes precedence - ie. :meta settings are ignored when code is hidden. 

Another approach would be to add to the valid options for `:code` - something like `#{:hide, :show, :fold, :show+meta, :fold+meta}`, or maybe `:verbatim` / `:literal` to encompass any future processing steps that might take place.

**Comment by mk** [comment]
@yuhan0 yes, viewers are late-binding and can be rebound by name and it's a central part of the viewer api. Because evaluation happens before presentation (the transformation of the result of eval to be sent over to the browser) it's possible to re-assign the viewers also further down in the document. Another example where we're using this is http://github.com/nextjournal/clerk-slideshow.
