### ISSUE TITLE
Lazy loading with java 8

### ISSUE THREAD

**Issue by qrthey** [nextjournal/clerk#511]
The  [percent-decode function in webserver.clj](https://github.com/nextjournal/clerk/blob/main/src/nextjournal/clerk/webserver.clj#LL48C17-L48C31) uses an overload of `java.net.URLDecoder/decode` that is not supported in java 8. 

While I have not observed other problems with Clerk in java 8, this results in an error when the user wants to load more values from a lazy sequence. On pressing the `more...` button, the button is just removed from the browser dom.

Is there a reason not to use ` (java.net.URLDecoder/decode s "UTF-8")`  in this case?

**Comment by mk** [comment]
We've decided to target Java 11+ with Clerk. There's more and more libraries with the same requirement these days (for example, we've been wanting to upgrade graal.js in https://github.com/nextjournal/markdown which also requires Java 11 in recent versions). So I think trying to keep compatibility with Java 8 will just be more and more of an upstream battle and I'd like us to spend our time elsewhere.

**Comment by mk** [comment]
I've added the Java 11 requirement in the docs in attached commit.

**Comment by qrthey** [comment]
Fair enough, and I actually agree. At work we are still obligued to run java 8 though, and there they use the 'it still has security updates for many years to come'... So I asked in case this was the only change required to support the ancient java version.
