### ISSUE TITLE
Tap viewer (`nextjournal.clerk.tap`) open/collapse state resets on calls to `tap>`

### ISSUE THREAD

**Issue by teodorlu** [nextjournal/clerk#543]
Using `io.github.nextjournal/clerk {:mvn/version "0.14.919"}`, the tap viewer does not remember open/collapsed state. To see new tap data (in expanded state), I have to re-open the viewer.

Steps to reproduce:

1. Call `(nextjournal.clerk/show! 'nextjournal.clerk.tap)`
2. `(tap> big-map)`

![image](https://github.com/nextjournal/clerk/assets/5285452/12e98e97-f64c-4761-aba5-b518199e83be)

4. Open the tap viewer

![image](https://github.com/nextjournal/clerk/assets/5285452/616338b2-c834-4f81-9880-f6af6c83fc23)

5. `(tap> new-big-map)`

**Expected behavior:** Tap viewer stays in opened state (for stream view and for latest view).

**Observed behavior**: Tap viewer collapses, and must be opened again.

When tapping many values, this leads to many clicks to open the object browser. I'd prefer less clicks!

![image](https://github.com/nextjournal/clerk/assets/5285452/6ea1ae3c-5ad7-46ac-987c-59e91ec5272d)

More details in this Slack thread: https://clojurians.slack.com/archives/C035GRLJEP8/p1691945268545999?thread_ts=1691928052.140139&cid=C035GRLJEP8

**Comment by mk** [comment]
@teodorlu thanks for creating the issue. I'm less sure that a new tapped value should inherit the expansion state of the one before but in the stream view the expanded value should preserve its expansion state for sure.

**Comment by teodorlu** [comment]
> I'm less sure that a new tapped value should inherit the expansion state of the one before

Yeah, good point—if we're tapping different types of values, it probably doesn't make sense to inherit the view properties of the last tapped value. Perhaps a checkbox to change set the default to expanded is an option.
