### ISSUE TITLE
Unqualified symbol when built in CI

### ISSUE THREAD

**Issue by elken** [nextjournal/clerk#545]
I recently refactored my aoc solution repo to clean up the index, and after [that commit](https://github.com/elken/aoc/commit/572db889b24bc156bcf4537f22e040620f2896c7); [the CI](https://github.com/elken/aoc/actions/runs/5907210832/job/16024740252) complains with 

`:path-fn must be a qualified symbol pointing at an existing var`

Despite that still being the case. What's even _stranger_ is it only occurs in CI...

![image](https://github.com/nextjournal/clerk/assets/2872862/848d28d6-34ec-436a-a226-5e3e6d5de811)

As above, when I clone a fresh repo there's no such error; so I'm completely stumped here :sweat_smile: Any ideas?

**Comment by elken** [comment]
No good resolution here; I wasn't aware `:paths` can take wildcards so I just went for that instead now.

**Comment by mk** [comment]
My first guess would be a classpath issue. Could the var be in a path brought in by an alias and not in use in CI?

**Comment by elken** [comment]
> My first guess would be a classpath issue. Could the var be in a path brought in by an alias and not in use in CI?

Potentially, but that doesn't explain how it was only failing in CI. I tried the same steps in a fresh Ubuntu image locally and it worked fine :/
