### ISSUE TITLE
clerk/show! the user ns?

### ISSUE THREAD

**Issue by hoclun-rigsep** [nextjournal/clerk#551]
If I just fire up a repl and run 

```
(require '[nextjournal.clerk :as clerk])
(clerk/serve!)
(clerk/show! (find-ns 'user))
```
it doesn't work:

> `nextjournal.clerk/show!` could not find a resource on the classpath for: `user`

I have a feeling this is expected but was curious if there is a workaround or so.

**Comment by mk** [comment]
It works for me here. If I had to guess I'd say the user namespace file can't be found on the classpath. What does the following return for you?

```clojure
(some (fn [ext]
        (clojure.java.io/resource (str (clojure.string/replace (namespace-munge 'user) "." "/") ext)))
      [".clj" ".cljc"])
;; => #object[java.net.URL 0x480f9816 "file:/Users/mk/dev/clerk/dev/user.clj"]
```

**Comment by hoclun-rigsep** [comment]
Thanks @mk. That expression returns nil for me.
