### ISSUE TITLE
Case where `clerk/row` displays only the first of its arguments

### ISSUE THREAD

**Issue by teodorlu** [nextjournal/clerk#567]
Hi!

I have a document where

```clojure
(clerk/row
 (scale ipe300 0.5)
 (scale hea300 0.5))
```

only displays the first value, `(scale ipe300 0.5)`. I was expecting both values to be shown.

Full document: [github] / [clerk garden]. Document screenshot:

[github]: https://github.com/teodorlu/lab/tree/5ca4e315740d669212626a056cd7e395d950d85c/src/repro/clerk_row_surprising.clj
[clerk garden]: https://github.clerk.garden/teodorlu/lab/commit/b32885c643ee8ab89e5ccfac6616c5e0154401de/src/repro/clerk_row_surprising.html

![image](https://github.com/nextjournal/clerk/assets/5285452/ea01195d-ce5f-4b2e-ae8c-ce50d7c69d9f)

**Comment by teodorlu** [comment]
Simpler reproduction:

```clojure
(clerk/row {:item 1} {:item 2})
```

Expected: both items are shown.
Actual: only last item is shown.

<img width="892" alt="image" src="https://github.com/nextjournal/clerk/assets/5285452/49d07133-7290-473c-9f7c-b708df8c035c">

Fix: wrap both in a vector. Perhaps I should have been doing this all along?

<img width="903" alt="image" src="https://github.com/nextjournal/clerk/assets/5285452/67842f90-f8e7-4373-92f9-3e73b5b1b2f5">

Images produced with `io.github.nextjournal/clerk {:mvn/version "0.15.957"}`.

**Comment by mk** [comment]
@teodorlu thanks for the report & repro!

We also support passing a viewer opts map as the first argument and the heuristic to decide is overly simplistic. Until we implement a proper fix, here's two workarounds:
```clojure
;; use single seq argument
(clerk/row [(scale ipe300 0.5)
            (scale hea300 0.5)])

;; wrap first value in a `:nextjournal/value` key.
(clerk/row {:nextjournal/value (scale ipe300 0.5)}
           (scale hea300 0.5))
```

**Comment by teodorlu** [comment]
Right, makes sense. Thanks for explaining `:nextjournal/value`, TIL!
