### ISSUE TITLE
Custom CSS replaces existing one instead of enhancing it.

### ISSUE THREAD

**Issue by genmeblog** [nextjournal/clerk#67]
Calling below:

`(swap! config/!resource->url assoc "/css/viewer.css" "notebooks/custom.css")`

works as (probably) intended. However I don't think anyone wishes to build complete CSS for Clerk from the scratch. I think typical use case would be just to add/replace some (small) CSS subset. A couple of classes/ids.

What do you think?

**Comment by mk** [comment]
Actually, replacing the full stylesheet is actually the intended usage. Clerk currently uses tailwind 3's [play cdn](https://tailwindcss.com/docs/installation/play-cdn). This is a javascript script that generates the used classes on-demand (using a mutation observer on the dom). This is primarily intended as a dev affordance. 

When publishing in production, tailwind recommends to compile a custom stylesheet containing only the used classes.  So we have this abstraction as a way for a user to override the stylesheet, compile it with a different tailwind config or user-appended styles (that can again include the viewer.css) but after going down that road we realized we don't want to be in the business of running a css pipeline for folks.

Also note that you can add inline styles using the `html` viewer like so:
```clojure
^{:nextjournal.clerk/visibility :hide-ns}
(ns newlines
  (:require [nextjournal.clerk :as clerk]))

^{::clerk/viewer :html ::clerk/visibility :hide}
[:style ".my-custom-class { color: blue; background-color: red; border-radius: 5px;}"]

(clerk/html [:div.my-custom-class.p-2 [:h1 "Hello 👋"]])
```
<img width="1095" alt="Screen Shot 2022-02-02 at 10 22 00" src="https://user-images.githubusercontent.com/1187/152126591-a178a690-c571-43a0-b7c0-2a58badf042d.png">

Please let me know if that works for you.

**Comment by genmeblog** [comment]
Thank you, above solution sounds as a reasonable one. I think this is exactly what I need (inline CSS for a couple of custom classes). Need to try that still (be back soon with conclusions).

**Comment by genmeblog** [comment]
Works!
