### ISSUE TITLE
cannot control  overall with of clerk output

### ISSUE THREAD

**Issue by behrica** [nextjournal/clerk#68]

**Comment by mk** [comment]
In ec07ed2701fb82ecac94c786a1310d7e324cab18 I've added a notebook showing how to control result width:
<img width="1251" alt="Screen Shot 2022-02-02 at 09 11 26" src="https://user-images.githubusercontent.com/1187/152116850-1589a480-745f-4c64-8c1a-ada50dc2ae9e.png">

This is a duplicate of #54 but it was obviously not documented well enough.

**Comment by behrica** [comment]
I ment the 'default with' for all cells
