### ISSUE TITLE
cannot render verbatim text with new lines

### ISSUE THREAD

**Issue by behrica** [nextjournal/clerk#69]
(clerk/code  ) does it somehow,
but does soe magic, with sometimes might fail.

**Comment by mk** [comment]
Does using the html viewer not work for your use case?
<img width="432" alt="Screen Shot 2022-02-02 at 09 18 54" src="https://user-images.githubusercontent.com/1187/152117570-0477ff03-0a60-44a2-a5ad-6c3b6d633969.png">

**Comment by behrica** [comment]
yes. It would.
Can be closed
