### ISSUE TITLE
rendered code duplicates when a cljc notebook ns is reloaded

### ISSUE THREAD

**Issue by mhuebert** [nextjournal/clerk#70]
When I have a cljc notebook open and I save, shadow recompiles and all the code blocks render again below themselves, producing duplicates - eg. after 3 reloads: 

<img width="1015" alt="image" src="https://user-images.githubusercontent.com/165223/152146748-fb4ce4ca-0d43-4a99-95c1-d32d29c4df0c.png">

**Comment by mk** [comment]
I believe you fixed this with https://github.com/nextjournal/viewers/pull/47. Please re-open if it's still an issue.
