### ISSUE TITLE
SSR static app broke, but CI test passes

### ISSUE THREAD

**Issue by mk** [nextjournal/clerk#706]
Went back a few commits and haven't yet found a working version.

It's already blank in 352115ce862dffb2e4da2628a5743c9d4f1801ff https://snapshots.nextjournal.com/clerk-ssr/build/352115ce862dffb2e4da2628a5743c9d4f1801ff/index.html.

**Comment by borkdude** [comment]
f8377d6116ccecee00ecf1dcc2fa843555cac9d8 seems to be the first commit which breaks SSR Static app

**Comment by borkdude** [comment]
Subproblems:
- [ ] terrible dev experience running things on CI leading to slow feedback times
- [ ] ssr being broken, by some incompatiblity between what build! returns and render/init! expects
- [ ] ssr test not detecting the failure
- [ ] bonus mission: supporting async in ssr, a step towards sci async eval
