### ISSUE TITLE
inlined comments rendered as markdown text

### ISSUE THREAD

**Issue by genmeblog** [nextjournal/clerk#71]
Comments in the code (with single semicolon) should be included in the source not rendered below as a text.

```
(list 1 2 3) ; produce a list
```

is rendered as:

![image](https://user-images.githubusercontent.com/38646601/152204258-558194d1-c147-409b-90ee-148b884f8a4e.png)

**Comment by jackrusher** [comment]
Note that comments _inside forms_ render properly. I think we're just not checking for a newline after a given form to make sure the comment isn't part of the same block. Thanks for the report!

**Comment by genmeblog** [comment]
Oh! Indeed. Well, looks like I produce one-liners only :)

**Comment by genmeblog** [comment]
Again (or still) not working 

```
;; text before
(+ 3 4) ;; inline comment
;; text after
```

![image](https://user-images.githubusercontent.com/38646601/223433353-092e8ec1-2623-492c-80b4-c101d888c5ed.png)

**Comment by zampino** [comment]
Thanks (again) @genmeblog for reporting this. It's a regression from #324. I'll have a look.
