### ISSUE TITLE
Error loading more table items when using viewer metadata

### ISSUE THREAD

**Issue by krzsztf** [nextjournal/clerk#73]
Hi,

First of all, thanks for Clerk, its awesome ;)

I've encountered bug, that loading more items in table does not work, when using viewer metadata:

```
;; ## Given
(def numbers (into [] (for [a (range 100)]
                        [a])))

;; ## Click 'more' for this table works...
(clerk/table numbers)

;; ## .. but clicking more here causes "Error: No protocol method IStack.-peek defined for type object"
^{::clerk/viewer clerk/table}
numbers
```

I'm using `io.github.nextjournal/clerk {:mvn/version "0.5.346"}`

**Comment by mk** [comment]
This has been fixed in v0.12.707:
https://github.com/nextjournal/clerk/blob/0abef98cecc7e8d5528571902f67e7e54bb67f54/CHANGELOG.md?plain=1#L379
