### ISSUE TITLE
`b is null` on the index page of a static build

### ISSUE THREAD

**Issue by a1exsh** [nextjournal/clerk#732]
1. Clone the [Advent of Clerk repo](https://github.com/nextjournal/advent-of-clerk)
2. See it work in the Garden:  https://github.clerk.garden/a1exsh/advent-of-clerk-2024/commit/2401fe42669220673f4a8dc6b70682483fae7038/
3. Update deps to the current latest releases: https://github.com/a1exsh/advent-of-clerk-2024/commit/7d591635b26481b45a6ea325f5c135a30b8276e2
4. See it work no more: https://github.clerk.garden/a1exsh/advent-of-clerk-2024/commit/7d591635b26481b45a6ea325f5c135a30b8276e2/

Observations:
- The link now points to `.../day_00.clj/` instead of `.../day_00.html` as it used to:
  -  https://github.clerk.garden/a1exsh/advent-of-clerk-2024/commit/7d591635b26481b45a6ea325f5c135a30b8276e2/src/advent_of_clerk/day_00.clj/
  - https://github.clerk.garden/a1exsh/advent-of-clerk-2024/commit/2401fe42669220673f4a8dc6b70682483fae7038/src/advent_of_clerk/day_00.html
- After visiting the broken link, if I go back to the index page, I'm getting this:
![image](https://github.com/user-attachments/assets/d1b91ebd-5f78-4c7b-8127-beb8c2114271)
- In the local static build via `clj -X:nextjournal/clerk` the index page looks like the above right away.

**Comment by mk** [comment]
Thanks for the issue @a1exsh.

We had a breaking change in how urls work recently and this has been a known sore issue. Made a quick fix in the commit above and will think about how we can avoid this going forward.
