### ISSUE TITLE
Question: Width and Position of VL Images

### ISSUE THREAD

**Issue by thecontinium** [nextjournal/clerk#79]
I saw this closed [issue](https://github.com/nextjournal/clerk/issues/54) and have tried 

```clojure
(merge
  {:nextjournal/width :full}
(clerk/vl .....
```

which does set the full width correctly for the image but the image is not centred. 

Is there a way to control the width and keep the vl image in the centre ?

Cheers

**Comment by mk** [comment]
One easy way to center it is wrapping it in a `clerk/col`:

<img width="863" alt="Screen Shot 2023-02-10 at 12 36 10" src="https://user-images.githubusercontent.com/1187/218083077-19cf0418-b929-428a-9ed3-fc3d84dd0832.png">
