### ISSUE TITLE
qualified symbol renders without a namespace

### ISSUE THREAD

**Issue by genmeblog** [nextjournal/clerk#91]
Quoted symbol (or java static variable) is rendered without a namespace. Syntax quote is not rendered at all.

```
(import 'java.awt.Color)

Color/PINK ;; #object[java.awt.Color 0x363b171d "java.awt.Color[r=255,g=175,b=175]"]
'Color/PINK ;; Color/PINK
`Color/PINK ;; java.awt.Color/PINK
clerk/vl ;; #'nextjournal.clerk.viewer/vl
'clerk/vl ;; clerk/vl
`clerk/vl  ;; nextjournal.clerk/vl
```

**Comment by genmeblog** [comment]
![image](https://user-images.githubusercontent.com/38646601/154853722-da1fa893-e46b-4c3d-b2d1-f2340774bc6e.png)

**Comment by mk** [comment]
Good timing, I actually fixed this earlier today with dad9865e15101cc047efc17c7b15ea277f514176. Please try that sha.

**Comment by genmeblog** [comment]
Tried with newest version. Synthax quote is not rendered in the code block (but it's rendered). The rest looks ok.

**Comment by mk** [comment]
Better late then never: the syntax quote now also renders:
<img width="338" alt="Screen Shot 2023-02-05 at 19 27 15" src="https://user-images.githubusercontent.com/1187/216837887-7871b803-1547-4186-9767-92e532825ca3.png">
