### ISSUE TITLE
"class" object does not render in static export

### ISSUE THREAD

**Issue by behrica** [nextjournal/clerk#95]
![image](https://user-images.githubusercontent.com/127361/155027083-2ddc105d-405c-4540-9ff2-a3c739f5e07c.png)

Does not happen in "live" view from repl

**Comment by genmeblog** [comment]
It dissapears when you clear cache before generating static html

**Comment by behrica** [comment]
It is likely an interaction between the in-memory cache (which is not nippy based) an the on disk cache.
I read as well that "class" objects in Nippy get successfully "frozen", but  on thawing they get serialized into a map as above (so not throwing an exception). there are ways to "override this behavior" as well via configuration.

Clerk could as well decide just to "recompute" the value. it has the "form" present to do so.
Let's see what @mk  comes up with.

**Comment by mk** [comment]
This has been fixed with e5c00bb0473bfdf1562024879a5ff69ed3309477 and I added a test for it in fbfa0901e67ce18b5fd8ffd7403c9cad69410f51.
