### ISSUE TITLE
nextjournal.clerk/build-static-app! tries to open browser

### ISSUE THREAD

**Issue by behrica** [nextjournal/clerk#96]
running `nextjournal.clerk/build-static-app!` always tries to open a browser at `http://localhost:7778/build`

As I am not developing clerk itself, I never have something running on that port.
I think the "build-static-app" should not assume that there is a server running, and therefore not try to open `localhost:7778`

**Comment by borkdude** [comment]
You can specify `:browse false` but I think not opening a browser is a more reasonable default.

**Comment by mk** [comment]
There was a check before so this would only happen for clerk dev. I think we now want to start a static webserver in that case.
